# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [2]:
import numpy as np
a = np.random.randint(10,size=6)

print('list(a):',list(a))
print('a.tolist()',a.tolist())

b = np.random.randint(10,size=6).reshape(3,2)

print('list(b):',list(b))
print('b.tolist()',b.tolist())

# 把巢狀的array轉成巢狀的list


list(a): [7, 8, 2, 4, 0, 4]
a.tolist() [7, 8, 2, 4, 0, 4]
list(b): [array([0, 8]), array([2, 4]), array([9, 6])]
b.tolist() [[0, 8], [2, 4], [9, 6]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [5]:
import numpy as np

a = np.random.randint(10,size=6) #一維

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))


[2 6 8 9 5 9]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [6]:
b = np.random.randint(10, size=(3,4)) #二維

print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

[[6 7 7 0]
 [8 2 8 0]
 [4 0 2 1]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [7]:
c = np.random.randint(10, size=(2,3,2)) #三維

print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

[[[7 3]
  [2 8]
  [2 5]]

 [[8 1]
  [7 9]
  [9 8]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[7, 6, 7, 3, 7, 5]
[7, 6, 7, 3, 7, 5]


In [ ]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[5, 7, 4, 6], [9, 4, 0, 1], [9, 1, 2, 9]]
[array([5, 7, 4, 6]), array([9, 4, 0, 1]), array([9, 1, 2, 9])]


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[0, 4], [0, 1], [9, 5]], [[8, 7], [8, 2], [6, 0]]]
[array([[0, 4],
       [0, 1],
       [9, 5]]), array([[8, 7],
       [8, 2],
       [6, 0]])]


In [8]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    nwelist = []
    for obj in iterable:
        nwelist.append(tolist(obj))
    return list(nwelist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[2, 6, 8, 9, 5, 9]
[[6, 7, 7, 0], [8, 2, 8, 0], [4, 0, 2, 1]]
[[[7, 3], [2, 8], [2, 5]], [[8, 1], [7, 9], [9, 8]]]


In [9]:
#進階寫法
def tolist(iterable):  
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]
    
print(tolist(a))
print(tolist(b))
print(tolist(c))    

[2, 6, 8, 9, 5, 9]
[[6, 7, 7, 0], [8, 2, 8, 0], [4, 0, 2, 1]]
[[[7, 3], [2, 8], [2, 5]], [[8, 1], [7, 9], [9, 8]]]
